common: &common
  adapter: postgresql
  username: chaffeqa
  pool: 5
  encoding: unicode

development:
  <<: *common
  database: enpac_dev

test:
  <<: *common
  database: enpac_test

production:
  <<: *common
  database: enpac_production

